### ISSUE TITLE
ALU Add incorrectly implemented?

### ISSUE THREAD

**Issue by gabriellet** [DavidWatkins/Chip8-SystemVerilog#9]
This seems to be implemented for inputs of width 8. The inputs are both width 16. Could we clarify which this should actually be?

**Comment by DavidWatkins** [comment]
ALU should be input 16 bits and output 16 bits. If they need to be truncated, that can occur outside of the ALU. Or we can add an extra "8-bit-add" operation to the ALU if need be (but I don't think so)

**Comment by gabriellet** [comment]
I agree; truncate outside if necessary. I'll fix that.
